spring:
  application:
    name: grpc-client
  server:
    port: 8080

grpc:
  client:
    item:
      address: ${TEST_ADDR:localhost:9090}
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
    test:
      address: ${TEST_ADDR:localhost:9090}
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext

