spring:
  application:
    name: grpc

grpc:
  client:
    test:
      address: ${TEST_ADDR:localhost:9090}
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
